recipe_delight/config/routes.rb
Rails.application.routes.draw do
    
    resources :customers
  get 'sessions/new'

  post 'sessions/create'

  get 'sessions/destroy'

    resources :static_pages, :only => [:index]
    root :to => "static_pages#home"

end

recipe_delight/app/models/coupon.rb
class Coupon < ActiveRecord::Base
end

recipe_delight/app/models/customer.rb
class Customer < ActiveRecord::Base
        
    attr_accessible :email, :password, :password_confirmation, :length => { :maximum => 20 }
    has_secure_password


end

recipe_delight/app/models/item.rb
class Item < ActiveRecord::Base
end

recipe_delight/app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

recipe_delight/app/models/store.rb
class Store < ActiveRecord::Base
end

recipe_delight/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    def current_user
        session[:customer_id] = @current_user
    end
end

recipe_delight/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def update
  end
end

recipe_delight/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    customer = Customer.authenticate(params[:email], params[:password])
    if customer
    flash[:success] = "Welcome!"
    redirect_to root_path 
    else
        flash[:error] = "Sorry but the email/password does not mach."
        render 'new'
    end
  end

  def destroy
  end

  private

  def session_params
    params.require(:session).permit!
  end
end

recipe_delight/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def home

    end

    def index

    end
end

recipe_delight/app/helpers/application_helper.rb
module ApplicationHelper
end

recipe_delight/app/helpers/customers_helper.rb
module CustomersHelper
end

recipe_delight/app/helpers/sessions_helper.rb
module SessionsHelper
end

recipe_delight/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

recipe_delight/app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

recipe_delight/app/views/customers/destroy.html.erb
<h1>Customers#destroy</h1>
<p>Find me in app/views/customers/destroy.html.erb</p>

recipe_delight/app/views/customers/edit.html.erb
<h1>Customers#edit</h1>
<p>Find me in app/views/customers/edit.html.erb</p>

recipe_delight/app/views/customers/new.html.erb
<h1>Customers#new</h1>
<p>Find me in app/views/customers/new.html.erb</p>

recipe_delight/app/views/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>

recipe_delight/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeDelight</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="row full_page">
         <div class="large-2 columns">
            <p>Sidebar on the left</p>
         </div>
         <div class="large-8 columns">
            
            <div class="row">
                <div class="large-12 columns" align="center">
                    <% flash.each do |name, message| %>
                        <% if !name.nil? && !message.nil? %>
                            <div data-alert class="alert-box <%=name%> radius">
                                <p><%=message%></p>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <%= render 'static_pages/topbar' %>
            <div class="large-12 columns">
                
                <%= yield %>
            </div>
         </div>
         <div class="large-2 columns">
            <p>Sidebar on the right</p>
         </div>
       </div>
        
   </body>
</html>

recipe_delight/app/views/static_pages/_topbar.html.erb
<nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area"> 
        <li class="name"> 
            <h1><%= link_to "Home", root_path %></h1>
        </li> 
        <li class="toggle-topbar menu-icon">
            <a href="#"><span>Menu</span></a>
        </li> 
    </ul> 
    <section class="top-bar-section"> 
        <!-- Right Nav Section --> 
        <ul class="right"> 
            <li class="active">
                <%= link_to "Login", sessions_new_path %>
            </li> 
            <li class="has-dropdown"> 
                <a href="#">Menu Dropdown</a>
                <ul class="dropdown"> 
                    <li>
                        <a href="#">First link</a>
                    </li> 
                    <li class="active">
                        <a href="#">Active link</a>
                    </li> 
                </ul> 
            </li> 
        </ul> 
        
        <!-- Left Nav Section --> 
        <ul class="left"> 
            <li>
                <a href="#">Redirect</a>
            </li>
        </ul> 
    </section> 
</nav>

recipe_delight/app/views/static_pages/home.html.erb
   <p>This is the main content of the website</p>